### ISSUE TITLE
Lessons.church print options is a great upgrade!

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#224]
Is it possible to add it to the portal side of things? We’ve never had a print option on the portal side and that’s where most of our users are looking for it anyway. It would be nice when they delete a section within the portal for their app that it would also delete on a final copy that they may choose to print.

**Comment by Himali-Malvawala** [comment]
There's already a print option on the preview link, which is visible when we edit a schedule that works exactly like what's mentioned above. Hence, adding "preview/print" to the button so that it sticks out and people know that the print option is there too.

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/86650000/831e2f23-c147-417f-a379-d7f32dfb1610)

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/86650000/2186c25f-cd95-48b9-a6ab-a25310b9399d)
