### ISSUE TITLE
Section Edit Link

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#286]
The link to edit a section is called "Manually Select Colors" this is somewhat confusing to people who are trying to find where to set up a section or edit a section. This might be better named "Section Set Up" 
<img width="958" alt="Screen Shot 2024-05-21 at 4 08 18 PM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/127863068/74fd77ab-6f5a-41d4-ad6b-ba9a21c20f8a">

**Comment by jzongker** [comment]
Let's switch this to tabs.  So take away the "Manually Suggest Colors" link and then below Current Colors have two tabs, "Suggestions" and "Custom"

@tbyrd77 - The idea is that 90% of the time, people will just click on one of those premade color schemes in the Suggestion area instead of having to select the individual colors.  Le me know if I'm missing something.

**Comment by tbyrd77** [comment]
Are these changes deployed?
