### ISSUE TITLE
B1 Websites are not allowing domains to be linked

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#290]
I had a church reach out saying they could not connect their domain https://www.teleosacademy.org/ 

So I tested on a new domain https://www.arkcurriculum.com/

And I got the same Error:  Below is a screen shot of how I set up the cname and a record as described in this article https://support.churchapps.org/b1/website-admin/add-cname-record.html

<img width="1481" alt="Screenshot 2024-05-27 at 2 44 36 PM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/4b19a17d-5062-4ec7-bbeb-ece7d4f50486">

**Comment by jzongker** [comment]
Every now and then I have to restart the Caddy server for it to pick up new changes.  I did so and the sites are working now.  I'm going to take the urgent label off but leave the issue open.

The "www." records should be a CNAME pointing to proxy.b1.church

**Comment by jzongker** [comment]
I believe this is caused by adding the domains to B1 first before the DNS entries have been created.  Let's Encrypt tries to verify the DNS to generate the cert and fails.  Doing it in the other order fixes the problem.  I've added a relink button to re-attempt the cert after the DNS entries have been added in case people do it in the other order.

Also Updated caddy server to latest version which as a significant jump to 2.9.0.
