### ISSUE TITLE
Ability to add new people in teams has stoped working on the plans page.

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#297]
YOu are suppose to search if you can not find the person add them on the spot 

https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/2812dba8-2c02-4059-9a12-7455f3afd8e8

**Comment by vassbo** [comment]
Created a pull request with the change allowing you to create a new person when no search is found.

**Comment by mbyrdLCS** [comment]
This is not working again.

**Comment by mbyrdLCS** [comment]
In Order for this to work when the teachers login I belive their email has to be entered can we make that a required field when adding from this view?

**Comment by jzongker** [comment]
I think we should go ahead and covert this form to a modal dialog and just update the PersonAdd component to have a link to that dialog instead of the form.

On that modal, let's add an email field but make it optional.  We'll need to include a validation if the email they enter already exists.  Have it state "John Doe already existing with an email of john@doe.com, are you sure you wish to add Jon Doe?" (plugging in the data).  If they say yes, go ahead and create the person.  It's not too uncommon for a husband and wife to share an email address.

**Comment by Himali-Malvawala** [comment]
@jzongker @mbyrdLCS I've added the email field with validation and everything's up on staging. But I'm not pushing it to production since it's the weekend. So it'll be up this Monday.
