### ISSUE TITLE
Giving Option??

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#360]
WE had a church ask if they could use https://www.zeffy.com/ with chums it does look like a good deal somehow they are covering all the fees. I contacted their customer support about an APi and this is what I got 

Hi Micheal,

We do not have an open API. We integrate with other platforms through Zapier. If the church management system you're using is also integrated with Zapier, it means you could automatically push data from Zeffy into this other app.

Maryse
Customer Success | Succès Client
contact@zeffy.com

Just putting it up here to see if it is even possible if not no big deal just close this issue.

**Comment by jzongker** [comment]
I don't doubt it's possible, but I'm going to close because I don't think it's a good idea.  Part of using their platform is the requirement that we prompt users to also donate to zeffy which defaults to 9%.  I'm sure they've done the math to know the income they receive from this exceeds the expense of their payment gateway.  Users would be donating $109 to get $100 to the church vs $102.50 if they just check the box to cover the Stripe fee.

If we add a second donation gateway, I think Paypal would be the next logical candidate.

**Comment by jzongker** [comment]
That said, I wouldn't be opposed to having the option if Zeffy wants to contribute that code.  I just don't think it's worth us spending time on.
